# The Numpy Package

#### Importing and working with the package

In [ ]:
import numpy

In [5]:
numpy?

In [1]:
import numpy as np


#### Numpy data structures: arrays

In [21]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/random/__init__.py'>
File:        /opt/anaconda3/lib/python3.7/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator

In [25]:
a = np.random.random((3, 5))
np.size(a)
a.size
a.shape

(3, 5)

#### Extracting data from arrays

In [31]:
a[1]
a[1, :]
#a[:, 4]

array([0.20279975, 0.31588516, 0.76208156, 0.46488275, 0.35403575])

#### Converting other data structures to arrays

In [38]:
mylist = [['cat', 'dog'], ['squirrel', 'mouse'], ['anteater', 'bear']]

In [39]:
np.array(mylist)

array([['cat', 'dog'],
       ['squirrel', 'mouse'],
       ['anteater', 'bear']], dtype='<U8')

#### Element-wise mathematical operations

In [41]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))

In [48]:
np.add(first, second)
#np.subtract
#np.multiply
#np.divide

array([[1.76076531, 0.93484661, 1.39448729, 1.31697114],
       [0.51161706, 1.09629554, 1.71737255, 0.58312263],
       [1.26686419, 1.60684081, 0.77761352, 0.52146574]])

In [54]:
[1, 2, 3] + [4, 5, 6]
np.add([1, 2, 3], [4, 5, 6])

array([5, 7, 9])